---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - nicolas.aira
dependencies:
  - conda-forge::python=3.12
  - conda-forge::openjdk>=17,<22
  - nicolas.aira::rnartistcore=0.4.6
