FROM continuumio/miniconda3:latest

COPY modules/shuffle_and_fold/environment.yml /tmp/environment.yml
RUN conda env create -f /tmp/environment.yml && \
    conda clean -afy
ENV PATH /opt/conda/envs/shuffle_and_fold/bin:$PATH

WORKDIR /app
COPY bin/ bin/
RUN chmod +x bin/shuffle_and_fold.py
