name: generate_embeddings
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python>=3.8
  - pandas>=2.2,<3.0
  - numpy>=1.26,<3.0
  - networkx>=3.4,<4.0
  - psutil>=7.0,<8.0
  - pytorch-cuda=12.4
  - pytorch>=2.6
  - pip
  - git
  - pip:
    - torch-geometric>=2.6
    - git+https://github.com/nicoaira/GINFINITY.git#egg=ginfinity